### ISSUE TITLE
Javascript error on Windows

### ISSUE THREAD

**Issue by Hakker** [unreadablewxy/fs-viewer#28]
This is what comes up when I try to start it on windows with build 0.01.  To start with I don't have a user WXY.
[https://lithi.io/file/2uZ8.png](https://lithi.io/file/2uZ8.png)

**Comment by Noramire** [comment]
Agree, seems like building is broken, because it depends on @unreadablewxy paths.

**Comment by unreadablewxy** [comment]
Looks like a bug in the webpack loader for native modules, which I've forgotten to release. Making a fix

**Comment by unreadablewxy** [comment]
Fixed in 0.0.2
