### ISSUE TITLE
Installation docs?

### ISSUE THREAD

**Issue by rEnr3n** [unreadablewxy/fs-viewer#35]
How do I install this?

**Comment by unreadablewxy** [comment]
The windows build is just a 7zip archive (get the unarchiver at: https://www.7-zip.org/) unarchive and run the only executable in the directory

To install the .deb package on a debian derivative like ubuntu run `sudo dpkg -i PATH`. To install the rpm on a red-hat-esque system run `sudo rpm -i PATH`
