### ISSUE TITLE
Unable to un-select during Batch Tagging

### ISSUE THREAD

**Issue by keniisucodes** [unreadablewxy/fs-viewer#58]
Unable to de-select an image while doing batch tagging.

**Comment by unreadablewxy** [comment]
Try pressing `esc`, if the application doesn't focus, right click on the thumbnails to gain focus.

Think focus loss is a bit of a problem.

**Comment by unreadablewxy** [comment]
An update, fixes for all 3 are slated to land in 1.3.0

**Comment by unreadablewxy** [comment]
Fixed in 1.3.0, windows build failing due to a bug in the license compliance plugin, can't generate official build due to compliance with MIT license issue
