### ISSUE TITLE
.exe for 1.3.0

### ISSUE THREAD

**Issue by keniisucodes** [unreadablewxy/fs-viewer#61]
Will the latest release 1.3.0 be available in .exe / Windows? Noticed it wasn't added upon release.

**Comment by unreadablewxy** [comment]
`license-webpack-plugin` seems to have been broken by some packages only required on windows. This prevents us from automatically generating the attributions files, a legal requirement.

This shouldn't interfere with functionality, so it is possible to create a private build from the code. Install NPM v14, clone the code, run `npm install && npm run build && npm start` and things should just work.

**Comment by unreadablewxy** [comment]
Fixed in 1.3.1
