### ISSUE TITLE
[FEATURES REQUEST] A list of some ideas

### ISSUE THREAD

**Issue by masterofobzene** [unreadablewxy/fs-viewer#65]
If some of these have been implemented already, then sorry-

Here we go:

- Make the app menus easier to use from far distances, make them more visible (make them bigger) (use case: couch or bed with small portable keyboard)

- Be able to create Categories (like folders) would be really good.

- Let the use of external players (potplayer, MPC for example)

- Autoplaylists generated from the current search (for example: click a tag and play all content from that filtered search could create a playlist of all those files)

- Mix of pics and videos should be included in that "play all" feature.

- Don't know if implemented already: a Quit shortcut key (configurable please)

**Comment by unreadablewxy** [comment]
> Make the app menus easier to use from far distances, make them more visible (make them bigger) (use case: couch or bed with small portable keyboard)

UI Scaling, sure.

> Be able to create Categories (like folders) would be really good.

Doesn't tags already solve this problem?

> Let the use of external players (potplayer, MPC for example)

So a "launch with" option? Not quite sure if overlap with file browsers is a good idea at this point

> Autoplaylists generated from the current search (for example: click a tag and play all content from that filtered search could create a playlist of all those files)

How would this be different to the filtered files list? how does auto play lists differ from the filtered results a play one after another feature?

> Mix of pics and videos should be included in that "play all" feature.

Suppose expected behavior is wait X Seconds on images but play videos their entire length? or wait X seconds regardless?

> a Quit shortcut key (configurable please)

Alt + F4?

**Comment by masterofobzene** [comment]
> > Make the app menus easier to use from far distances, make them more visible (make them bigger) (use case: couch or bed with small portable keyboard)
> 
> UI Scaling, sure.
> 
> > Be able to create Categories (like folders) would be really good.

> Doesn't tags already solve this problem? 
**mmm no... you see, tags are great for searching and useful but having categories shown as folders give an easier ui access from far by removing the need for typing the tags, since i'm not very good at explaining this I will edit an image to ilustrate my idea:**
![imagen](https://user-images.githubusercontent.com/94469116/143773140-70c47120-b035-4c24-9f41-ff8b545067f8.png)
**This should be persistent, meaning that when you open the program, you should be able to see your collection tagged into these categories at startup.**
**At the first start your collection would be shown in a messy way since you didn't tagged them yet, but as you tag the collection and put them into categories, everything gets easier to find.**

> 
> > Let the use of external players (potplayer, MPC for example)
> 
> So a "launch with" option? Not quite sure if overlap with file browsers is a good idea at this point
**It would be an instant fix for "support more formats" feature request also. Besides the program could hand over the play part to the OS and focus on UI and tagging systems (navigation). Also avoids all kinds of re-encoding (don't know for sure if that is happening right now or not. All customizations on this department would be done on the respective players giving users more freedom (except for generated playlist from content filtered in fs-viewer which would be a must.)**
**If this is not an option then it would be good to add extensive support for different movie and pics formats and having some options on the player is important too for pics and vids (repeat options, shuffle every time you open a collection so you don't see the same in the same order everytime, remember volume)**


> > Autoplaylists generated from the current search (for example: click a tag and play all content from that filtered search could create a playlist of all those files)
> 
> How would this be different to the filtered files list? how does auto play lists differ from the filtered results a play one after another feature?
**Taking into account the above request for external players this would need to be configured somehow, if not, the player would only play the selected file or files in that folder instead of the files filtered in fs-viewer. In other words, you would expect to play what you see on fs-viewer but the player wouldn't know that and simply play a selected file and the next would depend on the external player config (which in the best scenario would be "play all files from folder" and no tags would be taken into account). An auto generated playlist would have to be temporal to avoid creating thousand of playlists**
**If the external player is not an option, then you are right, filtering by tags would be enough but the player should have more compatibility with formats and some playability options like the ones mentioned above**


> > Mix of pics and videos should be included in that "play all" feature.
> 
> Suppose expected behavior is wait X Seconds on images but play videos their entire length? or wait X seconds regardless?
**I would expect to play the whole videos and pics in the same playlist with the ability to skip to next and previous. I love the pics slideshow that is implemented right now. Again if the external player is enabled and the playlists too, the only thing to do is tell the player to play "all this files filtered in fs-viewer".**
**If external player is not an option, the idea is to play the whole videos as I think they are right now. The use is pretty close to what I'm asking, but a few options to the player would be appreciated. Gifs are also a different world because they are short and meant to be player in a loop... adding an option to play gifs X times and then continue would be a awesome.**


> > a Quit shortcut key (configurable please)
> 
> Alt + F4?

**Well yes, but a configurable key would be appreciated since I'm using a small Rii portable keyboard and key shortcuts are a pain in the ass on those. Having the ability to configure an exit key OR combo if people like those would be nice.**

**Comment by unreadablewxy** [comment]
So the program is following a similar design philosophy as VSCode, only build in what is conceivably needed by everyone. Extensions optimizes for the individual's needs

I don't think adding a "favorite tags" mode makes sense in the main program.

* However the tagging service exposes all the APIs needed to build this as an extension.
* The settings can be persisted as user preferences.

Don't really have a need for this though, so I'm probably not going to personally build it.

As for integrating with external programs, sounds tenuous. Hard to know when a program is done with a file, don't want hard coupling to specific programs. This project is not meant to have parity with Windows explorer.

**Comment by masterofobzene** [comment]
Well its your software so it's your decision.
I'll keep searching for another one that suits my needs better. 

regards
