### ISSUE TITLE
[FEATURE REQUEST] Make the windows movable

### ISSUE THREAD

**Issue by masterofobzene** [unreadablewxy/fs-viewer#66]
Be able to move the program window from the title bar like any other windows app, not by having to click the icon on the left.

**Comment by unreadablewxy** [comment]
Suppose we could always make it an option to have a title bar, but the default aesthetic we're going for is minimal UI chrome, max content.

**Comment by masterofobzene** [comment]
I'm not against that I like the idea of maximizing the content area, but having the option is always good :)
