### ISSUE TITLE
[BUG] Scrolling to the end goes back to the beginning

### ISSUE THREAD

**Issue by masterofobzene** [unreadablewxy/fs-viewer#67]
Not sure if intentional but when in fullscreen, after reaching the end, the scroll will go to the very beginning and that is a little confusing/disorienting.

**Comment by unreadablewxy** [comment]
Having trouble reproing this, what's the window dimensions in pixels?

**Comment by masterofobzene** [comment]
Its happening only on fullscreen mode. I'm on 3840 X 2160 desktop res.
